import StrRender from "./StrRender";
import EpubRender from "./EpubRender";
import MobiRender from "./MobiRender";
import TxtRender from "./TxtRender";
import ComicRender from "./ComicRender";
import Fb2Render from "./Fb2Render";
declare var window: any;
window.e = window.eval;
window.a = window.atob;
export { StrRender, EpubRender, MobiRender, TxtRender, ComicRender, Fb2Render };
